import client from "@/api/lib/prisma-client"
import { Prisma } from "@prisma/client"
import { DEFAULT_KEYS } from "@/lib/default-keys/encrypt";
import { importPrivateKey, importPublicKey } from "@/lib/import-export-key";
import { encrypt } from "@/lib/encrypt";

const keys = await Array.fromAsync(
  DEFAULT_KEYS.map(async ({ publicKey, privateKey, digest }) => {
    return {
      publicKey: await importPublicKey(publicKey, false),
      privateKey: await importPrivateKey(privateKey, false),
      digest
    }
  })
)

// Generated by GhatGPT(4o mini)
const posts: Prisma.PostCreateManyArgs['data'] = [
  {
    encrypted_body: await encrypt('良い週末を！', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: null,
    ip_address: "198.51.100.75",
    created_at: new Date("2024-12-28T18:59:02Z"),
  },
  {
    encrypted_body: await encrypt('Darknetについて知りたい', keys[2].publicKey),
    public_key_digest: keys[2].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.10",
    created_at: new Date("2024-12-29T06:45:18Z"),
  },
  {
    encrypted_body: await encrypt('新しい暗号アルゴリズムについて話そう', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.200",
    created_at: new Date("2024-12-29T08:35:43Z"),
  },
  {
    encrypted_body: await encrypt('The decentralized web is coming!', keys[2].publicKey),
    public_key_digest: keys[2].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "198.51.100.155",
    created_at: new Date("2024-12-30T15:22:59Z"),
  },
  {
    encrypted_body: await encrypt('解決策を提供しよう', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "192.0.2.90",
    created_at: new Date("2024-12-30T10:47:11Z"),
  },
  {
    encrypted_body: await encrypt('未来は暗号で守られる', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.55",
    created_at: new Date("2024-12-31T13:55:02Z"),
  },
  {
    encrypted_body: await encrypt('Crypto is life!', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "192.168.0.123",
    created_at: new Date("2024-12-31T21:11:34Z"),
  },
  {
    encrypted_body: await encrypt('今日もプライバシーを守ろう', keys[2].publicKey),
    public_key_digest: keys[2].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.130",
    created_at: new Date("2025-01-01T19:42:19Z"),
  },
  {
    encrypted_body: await encrypt('I love cryptography!', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: null,
    ip_address: "192.168.1.99",
    created_at: new Date("2025-01-01T17:18:26Z"),
  },
  {
    encrypted_body: await encrypt('おやすみなさい', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "198.51.100.30",
    created_at: new Date("2025-01-02T22:05:47Z"),
  },
  {
    encrypted_body: await encrypt('Secure your data, always!', keys[2].publicKey),
    public_key_digest: keys[2].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.68",
    created_at: new Date("2025-01-02T16:23:14Z"),
  },
  {
    encrypted_body: await encrypt('昨日の会議は面白かった', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: null,
    ip_address: "192.0.2.78",
    created_at: new Date("2025-01-03T11:00:01Z"),
  },
  {
    encrypted_body: await encrypt('気になるニュースを見た', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: null,
    ip_address: "198.51.100.200",
    created_at: new Date("2025-01-03T12:34:56Z"),
  },
  {
    encrypted_body: await encrypt('New update coming soon!', keys[2].publicKey),
    public_key_digest: keys[2].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "203.0.113.100",
    created_at: new Date("2025-01-04T08:00:23Z"),
  },
  {
    encrypted_body: await encrypt('暗号掲示板で何しようか？', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: null,
    ip_address: "192.168.1.50",
    created_at: new Date("2025-01-04T10:15:50Z"),
  },
  {
    encrypted_body: await encrypt('ねむいけど仕事', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.45",
    created_at: new Date("2025-01-05T14:22:30Z"),
  },
  {
    encrypted_body: await encrypt('Blockchain is the future!', keys[2].publicKey),
    public_key_digest: keys[2].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "192.0.2.25",
    created_at: new Date("2025-01-05T22:32:45Z"),
  },
  {
    encrypted_body: await encrypt('今日も元気にプログラミング！', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: null,
    ip_address: "198.51.100.101",
    created_at: new Date("2025-01-06T03:45:27Z"),
  },
  {
    encrypted_body: await encrypt('暗号技術最高！', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: null,
    ip_address: "203.0.113.15",
    created_at: new Date("2025-01-06T05:15:32Z"),
  },
  {
    encrypted_body: await encrypt('Hello Crypto!', keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "192.168.0.1",
    created_at: new Date("2025-01-06T04:13:07Z"),
  },
  {
    encrypted_body: await encrypt('ねむい', keys[1].publicKey),
    public_key_digest: keys[1].digest,
    verify_key_digest: null,
    ip_address: "192.168.0.2",
    created_at: new Date("2025-01-08T10:22:19Z"),
  },
  {
    encrypted_body: await encrypt("ここにメッセージ", keys[0].publicKey),
    public_key_digest: keys[0].digest,
    verify_key_digest: "h9Kv5e7imUtD73F7gAcxGp",
    ip_address: "192.168.0.3",
    created_at: new Date("2025-01-11T16:01:13Z"),
  },
];

// 仮
const verifyKeys: Prisma.VerifyKeyCreateManyArgs['data'] = [
  {
    "digest": "wAcrImJaLu2iwSz+q428Z7",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "h9Kv5e7imUtD73F7gAcxGp",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "xqfzLPkrk4Is8cOBuA5W5v",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "u8O9cFPoyWlxs1q7SlLPkA",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "L59BAs8nVUmfmxOTM6v60n",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "4h7t9c4xUquF9rx72yB9B3",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "FplCr4Tcu4bFdkQ2tzFREz",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  },
  {
    "digest": "9m3qA6xOdj6bxUQ8rFhzGh",
    "ip_address": "192.168.0.1",
    "created_at": new Date(),
    "verify_key": "U0w1eXegjZXVQaNCjH2UQWaEhmio9Zb6IHG+gvzOG0EBOFimqy9IrG/oX3fR8JO/jsbIZNrICmfKqgkTUWN2F8eVChjGFi72dNxazcUsvAJp9VL5ObnzKnA4LMiPFLZVQx5yMG7jf0WobjsyZj3BglI+0DBX1nAvbqpoO2fZDs252EN++cJAL+ytIkWUPiaXIHX4/knAyXrGvo529Ke5iyOU6O1KZn1RRi9/7L43Vgb/Zo606CRgaTGZgpn7czJbYP47FfVXKH+3dK/yjWKqtJxotWjAerKdRNog8aF8YzP8yZIlaDHFSrEdQSEc00807GAOtLJD/hspKb+kLQeyOMWY1w/4HSPYU1yMcUbvDuG5IXAXFwou3AqGpkJVR71vSfIVGnf6ZFIGWjHW6/5OGo2s455EjePS2imWh2N/uxSHhEY+0c7"
  }
]

async function seedPosts() {
  await client.verifyKey.deleteMany()
  await client.verifyKey.createMany({ data: verifyKeys })
  await client.post.deleteMany()
  await client.post.createMany({ data: posts })
}

await seedPosts()
console.log('シードデータの適用が完了しました')